CREATE TABLE `books` (
	`book_id` INT(10) NOT NULL,
	`goodreads_book_id` INT(10) NOT NULL,
	`best_book_id` INT(10) NOT NULL,
	`work_id` INT(10) NOT NULL,
	`books_count` INT(10) NOT NULL,
	`isbn` VARCHAR(50) NULL DEFAULT NULL,
	`isbn13` VARCHAR(50) NULL DEFAULT NULL,
	`authors` VARCHAR(150) NULL DEFAULT NULL,
	`original_publication_year` VARCHAR(10) NULL DEFAULT NULL,
	`original_title` VARCHAR(150) NULL DEFAULT NULL,
	`title` VARCHAR(150) NULL DEFAULT NULL,
	`language_code` VARCHAR(50) NULL DEFAULT NULL,
	`average_rating` FLOAT NOT NULL,
	`ratings_count` INT(12) NOT NULL,
	`work_ratings_count` INT(12) NOT NULL,
	`work_text_reviews_count` INT(12) NOT NULL,
	`ratings_1` INT(12) NOT NULL,
	`ratings_2` INT(12) NOT NULL,
	`ratings_3` INT(12) NOT NULL,
	`ratings_4` INT(12) NOT NULL,
	`ratings_5` INT(12) NOT NULL,
	`image_url` VARCHAR(200) NULL DEFAULT NULL,
	`small_image_url` VARCHAR(200) NULL DEFAULT NULL,
	PRIMARY KEY (`book_id`)
);